# **AI And Biotechnology/Bioinformatics**

## **AI and Drug Discovery Course: QSAR Modeling**
This notebook demonstrates how to collect and preprocess bioactivity data from ChEMBL for QSAR modeling

# **Part 1: Data Collection & Curation**

**First we need to connect Google Colab with our Google Drive, so that we can have access to our Google drive within Colab.**

This allows us to:
* Save datasets
* Reload data across sessions
* Organize project files

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

**Now create "data" folder in our "Colab Notebooks" folder on Google Drive.**

In [ ]:
! mkdir "/content/gdrive/My Drive/Colab Notebooks/data"

## Install and Import Required Libraries
We install the ChEMBL web service package so that we can retrieve bioactivity data

In [ ]:
!pip install chembl_webresource_client

Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.9-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.32.4)
Collecting requests-cache~=1.2 (from chembl_webresource_client)
  Downloading requests_cache-1.2.1-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: easydict in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.1.4)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (25.4.0)
Collecting cattrs>=22.2 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading cattrs-25.3.0-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.5.1)
Collecting url-normalize>=1.4 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading url_normalize-2.2.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.15.0)
Downloading chembl_webresource_client-0.10.9-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 3.0 MB/s eta 0:00:00
Downloading requests_cache-1.2.1-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.4/61.4 kB 4.8 MB/s eta 0:00:00
Downloading cattrs-25.3.0-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.7/70.7 kB 5.9 MB/s eta 0:00:00
Downloading url_normalize-2.2.1-py3-none-any.whl (14 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, chembl_webresource_client
Successfully installed cattrs-25.3.0 chembl_webresource_client-0.10.9 requests-cache-1.2.1 url-normalize-2.2.1

# Import Libraries
* pandas for data handling
* new_client from chembl for accessing the database

In [ ]:
import pandas as pd
from chembl_webresource_client.new_client import new_client

# **Step 1: Search for Traget Protein**

## **Target Identification (TK1)**
Search ChEMBL for the TK1 target and select the most relevant entry.

In [ ]:
target = new_client.target
target_query = target.search("TK1")
targets = pd.DataFrame.from_dict(target_query)
targets.head(8)

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,"Thymidine kinase, cytosolic",19.0,False,CHEMBL2883,"[{'accession': 'P04183', 'component_descriptio...",SINGLE PROTEIN,9606
1,[],Mus musculus,"Thymidine kinase, cytosolic",19.0,False,CHEMBL2618,"[{'accession': 'P04184', 'component_descriptio...",SINGLE PROTEIN,10090
2,[],Rattus norvegicus,"Thymidine kinase, cytosolic",19.0,False,CHEMBL4022,"[{'accession': 'P27158', 'component_descriptio...",SINGLE PROTEIN,10116
3,[],Cricetulus griseus,"Thymidine kinase, cytosolic",19.0,False,CHEMBL3227916,"[{'accession': 'P09768', 'component_descriptio...",SINGLE PROTEIN,10029

**Reterive Bioactivity data for selected target**

In [ ]:
selected_target = targets.target_chembl_id[0]
selected_target

'CHEMBL2883'

**Now retrieve only bioactivity data for target; **Thymidine kinase 1 (CHEMBL2883)** with reported IC50  values in nM (nanomolar) unit.**

In [ ]:
activity = new_client.activity
results = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [ ]:
df1 = pd.DataFrame.from_dict(results)
df1.head(10)

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,431782,[],CHEMBL811735,Inhibitory concentration on phosphorylation of...,B,None,None,BAO_0000190,...,Homo sapiens,"Thymidine kinase, cytosolic",9606,None,None,IC50,uM,UO_0000065,None,28.0
1,None,None,431783,[],CHEMBL816579,Inhibitory concentration on phosphorylation of...,F,None,None,BAO_0000190,...,Homo sapiens,"Thymidine kinase, cytosolic",9606,None,None,IC50,uM,UO_0000065,None,72.0
2,None,Not Determined,431784,[],CHEMBL811733,Inhibitory concentration on phosphorylation of...,B,None,None,BAO_0000190,...,Homo sapiens,"Thymidine kinase, cytosolic",9606,None,None,IC50,uM,UO_0000065,None,None
3,None,None,438271,[],CHEMBL811735,Inhibitory concentration on phosphorylation of...,B,None,None,BAO_0000190,...,Homo sapiens,"Thymidine kinase, cytosolic",9606,None,None,IC50,uM,UO_0000065,None,180.0
4,None,None,438272,[],CHEMBL816579,Inhibitory concentration on phosphorylation of...,F,None,None,BAO_0000190,...,Homo sapiens,"Thymidine kinase, cytosolic",9606,None,None,IC50,uM,UO_0000065,None,500.0
5,None,Not Determined,438273,[],CHEMBL811733,Inhibitory concentration on phosphorylation of...,B,None,None,BAO_0000190,...,Homo sapiens,"Thymidine kinase, cytosolic",9606,None,None,IC50,uM,UO_0000065,None,None
6,None,None,440825,[],CHEMBL811735,Inhibitory concentration on phosphorylation of...,B,None,None,BAO_0000190,...,Homo sapiens,"Thymidine kinase, cytosolic",9606,None,None,IC50,uM,UO_0000065,None,3.5
7,None,None,440826,[],CHEMBL816579,Inhibitory concentration on phosphorylation of...,F,None,None,BAO_0000190,...,Homo sapiens,"Thymidine kinase, cytosolic",9606,None,None,IC50,uM,UO_0000065,None,500.0
8,None,None,440827,[],CHEMBL815702,Inhibitory concentration on phosphorylation of...,B,None,None,BAO_0000190,...,Homo sapiens,"Thymidine kinase, cytosolic",9606,None,None,IC50,uM,UO_0000065,None,500.0
9,None,None,443567,[],CHEMBL811735,Inhibitory concentration on phosphorylation of...,B,None,None,BAO_0000190,...,Homo sapiens,"Thymidine kinase, cytosolic",9606,None,None,IC50,uM,UO_0000065,None,33.0

In [ ]:
df1.standard_type.unique()

array(['IC50'], dtype=object)

**Finally Save the resulting bioactivity data to a CSV file** **bioactivity_raw_data.csv**.

In [ ]:
df1.to_csv('bioactivity_raw_data.csv', index=False)

**Now copy "bioactivity_raw_data.csv" file to Google Drive, in folder "data"**

In [ ]:
! cp bioactivity_raw_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"

In [ ]:
! ls -l "/content/gdrive/My Drive/Colab Notebooks/data"

total 145
-rw------- 1 root root 148240 Jan 29 20:20 bioactivity_raw_data.csv

In [ ]:
! head bioactivity_raw_data.csv

action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,bao_label,canonical_smiles,data_validity_comment,data_validity_description,document_chembl_id,document_journal,document_year,ligand_efficiency,molecule_chembl_id,molecule_pref_name,parent_molecule_chembl_id,pchembl_value,potential_duplicate,qudt_units,record_id,relation,src_id,standard_flag,standard_relation,standard_text_value,standard_type,standard_units,standard_upper_value,standard_value,target_chembl_id,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
,,431782,[],CHEMBL811735,Inhibitory concentration on phosphorylation of [methyl-3H]-dTh by human Thymidine Kinase 2,B,,,BAO_0000190,BAO_0000357,single protein format,Cc1cn(C/C=C\CNC(=O)c2cccc(C(F)(F)F)c2)c(=O)[nH]c1=O,,,CHEMBL1144975,Bioorg Med Chem Lett,2003,"{'bei': '12.39', 'le': '0.24', 'lle': '2.70', 'sei': '5.42'}",CHEMBL431234,,CHEMBL431234,4.55,0,http://www.openphacts.org/units/Nanomolar,191914,=,1,1,=,,IC50,nM,,28000.0,CHEMBL2883,Homo sapiens,"Thymidine kinase, cytosolic",9606,,,IC50,uM,UO_0000065,,28.0
,,431783,[],CHEMBL816579,Inhibitory concentration on phosphorylation of [methyl-3H]-dTh by HSV-1 Thymidine Kinase,F,,,BAO_0000190,BAO_0000019,assay format,Cc1cn(C/C=C\CNC(=O)c2cccc(C(F)(F)F)c2)c(=O)[nH]c1=O,,,CHEMBL1144975,Bioorg Med Chem Lett,2003,,CHEMBL431234,,CHEMBL431234,4.14,0,http://www.openphacts.org/units/Nanomolar,191914,=,1,1,=,,IC50,nM,,72000.0,CHEMBL2883,Homo sapiens,"Thymidine kinase, cytosolic",9606,,,IC50,uM,UO_0000065,,72.0
,Not Determined,431784,[],CHEMBL811733,Inhibitory concentration on phosphorylation of [methyl-3H]-dTh by human Thymidine Kinase 1; Not determined,B,,,BAO_0000190,BAO_0000357,single protein format,Cc1cn(C/C=C\CNC(=O)c2cccc(C(F)(F)F)c2)c(=O)[nH]c1=O,,,CHEMBL1144975,Bioorg Med Chem Lett,2003,,CHEMBL431234,,CHEMBL431234,,0,http://www.openphacts.org/units/Nanomolar,191914,,1,0,,,IC50,nM,,,CHEMBL2883,Homo sapiens,"Thymidine kinase, cytosolic",9606,,,IC50,uM,UO_0000065,,
,,438271,[],CHEMBL811735,Inhibitory concentration on phosphorylation of [methyl-3H]-dTh by human Thymidine Kinase 2,B,,,BAO_0000190,BAO_0000357,single protein format,Cc1cn(C/C=C\CN2CCN(Cc3ccccc3)CC2)c(=O)[nH]c1=O,Outside typical range,"Values for this activity type are unusually large/small, so may not be accurate",CHEMBL1144975,Bioorg Med Chem Lett,2003,,CHEMBL441814,,CHEMBL441814,,0,http://www.openphacts.org/units/Nanomolar,191905,=,1,1,=,,IC50,nM,,180000.0,CHEMBL2883,Homo sapiens,"Thymidine kinase, cytosolic",9606,,,IC50,uM,UO_0000065,,180.0
,,438272,[],CHEMBL816579,Inhibitory concentration on phosphorylation of [methyl-3H]-dTh by HSV-1 Thymidine Kinase,F,,,BAO_0000190,BAO_0000019,assay format,Cc1cn(C/C=C\CN2CCN(Cc3ccccc3)CC2)c(=O)[nH]c1=O,Outside typical range,"Values for this activity type are unusually large/small, so may not be accurate",CHEMBL1144975,Bioorg Med Chem Lett,2003,,CHEMBL441814,,CHEMBL441814,,0,http://www.openphacts.org/units/Nanomolar,191905,>,1,1,>,,IC50,nM,,500000.0,CHEMBL2883,Homo sapiens,"Thymidine kinase, cytosolic",9606,,,IC50,uM,UO_0000065,,500.0
,Not Determined,438273,[],CHEMBL811733,Inhibitory concentration on phosphorylation of [methyl-3H]-dTh by human Thymidine Kinase 1; Not determined,B,,,BAO_0000190,BAO_0000357,single protein format,Cc1cn(C/C=C\CN2CCN(Cc3ccccc3)CC2)c(=O)[nH]c1=O,,,CHEMBL1144975,Bioorg Med Chem Lett,2003,,CHEMBL441814,,CHEMBL441814,,0,http://www.openphacts.org/units/Nanomolar,191905,,1,0,,,IC50,nM,,,CHEMBL2883,Homo sapiens,"Thymidine kinase, cytosolic",9606,,,IC50,uM,UO_0000065,,
,,440825,[],CHEMBL811735,Inhibitory concentration on phosphorylation of [methyl-3H]-dTh by human Thymidine Kinase 2,B,,,BAO_0000190,BAO_0000357,single protein format,Cc1cn(C/C=C\CN(Cc2ccccc2)Cc2ccccc2)c(=O)[nH]c1=O,,,CHEMBL1144975,Bioorg Med Chem Lett,2003,"{'bei': '14.53', 'le': '0.27', 'lle': '2.36', 'sei': '9.39'}",CHEMBL316971,,CHEMBL316971,5.46,0,http://www.openphacts.org/units/Nanomolar,191907,=,1,1,=,,IC50,nM,,3500.0,CHEMBL2883,Homo sapiens,"Thymidine kinase, cytosolic",9606,,,IC50,uM,UO_0000065,,3.5
,,440826,[],CHEMBL816579,Inhibitory concentration on phosphorylation of [methyl-3H]-dTh by HSV-1 Thymidine Kinase,F,,,BAO_0000190,BAO_0000019,assay format,Cc1cn(C/C=C\CN(Cc2ccccc2)Cc2ccccc2)c(=O)[nH]c1=O,Outside typical range,"Values for this activity type are unusually large/small, so may not be accurate",CHEMBL1144975,Bioorg Med Chem Lett,2003,,CHEMBL316971,,CHEMBL316971,,0,http://www.openphacts.org/units/Nanomolar,191907,>,1,1,>,,IC50,nM,,500000.0,CHEMBL2883,Homo sapiens,"Thymidine kinase, cytosolic",9606,,,IC50,uM,UO_0000065,,500.0
,,440827,[],CHEMBL815702,Inhibitory concentration on phosphorylation of [methyl-3H]-dTh by human Thymidine Kinase 1,B,,,BAO_0000190,BAO_0000357,single protein format,Cc1cn(C/C=C\CN(Cc2ccccc2)Cc2ccccc2)c(=O)[nH]c1=O,Outside typical range,"Values for this activity type are unusually large/small, so may not be accurate",CHEMBL1144975,Bioorg Med Chem Lett,2003,,CHEMBL316971,,CHEMBL316971,,0,http://www.openphacts.org/units/Nanomolar,191907,>,1,1,>,,IC50,nM,,500000.0,CHEMBL2883,Homo sapiens,"Thymidine kinase, cytosolic",9606,,,IC50,uM,UO_0000065,,500.0

# **Step 2: Bioactivity Data Retrieval (IC50)**
**Retrieve bioactivity data (IC50) for the selected KLK3 target.**

**Inspect Missing Values**

In [ ]:
df1["standard_type"].isna().sum()

np.int64(0)

**Filter Rows with Valid Bioactivity Values**

In [ ]:
df2 = df1[df1["standard_value"].notna()]
df2.head()

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,431782,[],CHEMBL811735,Inhibitory concentration on phosphorylation of...,B,None,None,BAO_0000190,...,Homo sapiens,"Thymidine kinase, cytosolic",9606,None,None,IC50,uM,UO_0000065,None,28.0
1,None,None,431783,[],CHEMBL816579,Inhibitory concentration on phosphorylation of...,F,None,None,BAO_0000190,...,Homo sapiens,"Thymidine kinase, cytosolic",9606,None,None,IC50,uM,UO_0000065,None,72.0
3,None,None,438271,[],CHEMBL811735,Inhibitory concentration on phosphorylation of...,B,None,None,BAO_0000190,...,Homo sapiens,"Thymidine kinase, cytosolic",9606,None,None,IC50,uM,UO_0000065,None,180.0
4,None,None,438272,[],CHEMBL816579,Inhibitory concentration on phosphorylation of...,F,None,None,BAO_0000190,...,Homo sapiens,"Thymidine kinase, cytosolic",9606,None,None,IC50,uM,UO_0000065,None,500.0
6,None,None,440825,[],CHEMBL811735,Inhibitory concentration on phosphorylation of...,B,None,None,BAO_0000190,...,Homo sapiens,"Thymidine kinase, cytosolic",9606,None,None,IC50,uM,UO_0000065,None,3.5

**Assign Bioactivity Classes**
Define active, intermediate, and inactive classes based on IC50 values.

In [ ]:
bioactivity_class = []
for value in df2.standard_value:
    value = float(value)
    if value >= 10000:
        bioactivity_class.append("inactive")
    elif value <= 1000:
        bioactivity_class.append("active")
    else:
        bioactivity_class.append("intermediate")

**Extract Relevant Columns**

In [ ]:
molecule_ids = df2.molecule_chembl_id.tolist()
canonical_smiles = df2.canonical_smiles.tolist()
standard_values = df2.standard_value.tolist()

In [ ]:
data = list(zip(
    molecule_ids,
    canonical_smiles,
    standard_values,
        bioactivity_class,
))

**Create Preprocessed bioactivity Dataset**

In [ ]:

df3 = pd.DataFrame(
    data,
    columns=[
        "molecule_chembl_id",
        "canonical_smiles",
        "standard_value",
        "bioactivity_class",
    ]
)
df3.head()

,molecule_chembl_id,canonical_smiles,standard_value,bioactivity_class
0,CHEMBL431234,Cc1cn(C/C=C\CNC(=O)c2cccc(C(F)(F)F)c2)c(=O)[nH...,28000.0,inactive
1,CHEMBL431234,Cc1cn(C/C=C\CNC(=O)c2cccc(C(F)(F)F)c2)c(=O)[nH...,72000.0,inactive
2,CHEMBL441814,Cc1cn(C/C=C\CN2CCN(Cc3ccccc3)CC2)c(=O)[nH]c1=O,180000.0,inactive
3,CHEMBL441814,Cc1cn(C/C=C\CN2CCN(Cc3ccccc3)CC2)c(=O)[nH]c1=O,500000.0,inactive
4,CHEMBL316971,Cc1cn(C/C=C\CN(Cc2ccccc2)Cc2ccccc2)c(=O)[nH]c1=O,3500.0,intermediate

**Remove Compounds without Valid SMILES**. Drop rows with **NaN**, **empty** or **None** SMILES values.

In [ ]:
df3 = df3.dropna(subset=["canonical_smiles"])
df3 = df3[df3["canonical_smiles"].str.lower() != "none"]
df3 = df3[df3["canonical_smiles"].str.strip() != ""]
df3.head()

,molecule_chembl_id,canonical_smiles,standard_value,bioactivity_class
0,CHEMBL431234,Cc1cn(C/C=C\CNC(=O)c2cccc(C(F)(F)F)c2)c(=O)[nH...,28000.0,inactive
1,CHEMBL431234,Cc1cn(C/C=C\CNC(=O)c2cccc(C(F)(F)F)c2)c(=O)[nH...,72000.0,inactive
2,CHEMBL441814,Cc1cn(C/C=C\CN2CCN(Cc3ccccc3)CC2)c(=O)[nH]c1=O,180000.0,inactive
3,CHEMBL441814,Cc1cn(C/C=C\CN2CCN(Cc3ccccc3)CC2)c(=O)[nH]c1=O,500000.0,inactive
4,CHEMBL316971,Cc1cn(C/C=C\CN(Cc2ccccc2)Cc2ccccc2)c(=O)[nH]c1=O,3500.0,intermediate

**Save Preprocessed Bioactivity Data.** Save the cleaned dataset to CSV and copy to Google Drive.

In [ ]:
df3.to_csv("bioactivity_preprocessed_data.csv", index=False)

!cp bioactivity_preprocessed_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"
!ls "/content/gdrive/My Drive/Colab Notebooks/data"

bioactivity_preprocessed_data.csv  bioactivity_raw_data.csv

## **End of Part 1: Data Collection and Curation**